In [1]:
# 주피터 노트북 환경설정
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

from IPython.display import set_matplotlib_formats
set_matplotlib_formats("retina")

from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; font-family:'Malgun Gothic' !important;}</style>"))
display(HTML("<style>.container { font-weight: bold !important;}</style>"))
display(HTML("<style>.container { width: 98% !important; }</style>"))

In [2]:
# 모듈 임포트 
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#  한글글꼴로 변경
plt.rcParams['font.size'] = 12.0
plt.rcParams['font.family'] = 'Malgun Gothic'

# Quiz 

피마 인디언 당뇨병(Pima Indian Diabets) 데이터 세트를 이용해 당뇨병 여부를 판단하는 머신러닝 예측 모델을 수립하고 
테스트 하여라.

- 캐글 사이트에서 로그인후 다운로드 
https://www.kaggle.com/uciml/pima-indians-diabetes-database#

1) diabetes.csv 파일을 이용하여 데이타프레임을 생성하여라 
2) 결측값이 있는지 확인하여라. 
3) 각 피처별 최소값이 0으로 측정되는 데이타값을 평균값으로 변경하여라. 
4) StandardScaler()를 이용하여 스케일링하여라. 
5) 학습 데이타셋과 테스트 데이타셋으로 분리시키고 모델을 생성한 후 
   머신러닝 예측 모델을 수립하고 학습하여라 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
                                                        random_state = 156, stratify=y)
model_dt = DecisionTreeClassifier(random_state=11)

6) 오차행렬, 재현율, 정밀도, 정확도, F1 Score 등의 평가지표를 출력하여라 

7) 아래의 소스를 참조하여 그리드서치를 적용시켜 최고의 하이퍼파라미터 예측 모델을 생성하여라. 

model_dt = DecisionTreeClassifier(random_state=11)

parameters = {'max_depth':[2,3,5,10] }

model_dt_grid = GridSearchCV(model_dt , param_grid=parameters , scoring='accuracy' , cv=5)

<!-- 아래그림 확인 -->
<img src="https://thebook.io/img/080228/137.jpg">
<br>
<img src="http://health.chosun.com/site/data/img_dir/2005/09/29/c2005092956311_01.jpg">

* Pregnancies: 임신 횟수
* Glucose: 포도당 부하 검사 수치
* BloodPressure: 혈압(mm Hg)
* SkinThickness: 팔 삼두근 뒤쪽의 피하지방 측정값(mm)
* Insulin: 혈청 인슐린(mu U/ml)
* BMI: 체질량지수(체중(kg)/(키(m))^2)
* DiabetesPedigreeFunction: 당뇨 내력 가중치 값
* Age: 나이
* Outcome: 클래스 결정 값(0 또는 1)

In [3]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import cross_val_score 
# from sklearn.model_selection import GridSearchCV

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve, roc_auc_score
from sklearn.metrics import classification_report

In [4]:
# 1) diabetes.csv 파일을 이용하여 데이터프레임화 하기
diabetes = pd.read_csv('data/diabetes.csv')
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [7]:
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
X_diabetes = diabetes.loc[:, :'Age']
X_diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [9]:
Y_diabetes = diabetes['Outcome']
Y_diabetes

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [11]:
# 2) 결측값이 있는지 확인하여라.
X_diabetes.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [ ]:
# 3) 각 피처별 최소값이 0으로 측정되는 데이터값을 평균값으로 변경하여라
# min이 0이되는 것을 바꿔야 하는 열
# Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction

In [12]:
X_diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [14]:
for col in min_zero:
    X_diabetes[col ]=X_diabetes[col].apply(lambda x: X_diabetes[col].mean() if x==0 else x)

In [15]:
X_diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,4.400782,121.681605,72.254807,26.606479,118.660163,32.450805,0.471876,33.240885
std,2.984162,30.436016,12.115932,9.631241,93.080358,6.875374,0.331329,11.760232
min,1.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000
25%,2.000000,99.750000,64.000000,20.536458,79.799479,27.500000,0.243750,24.000000
50%,3.845052,117.000000,72.000000,23.000000,79.799479,32.000000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [ ]:
# for col in min_zero:
#     df[col] = df[col].apply(lambda x: df[col].mean() if x==0 else x) # 컬럼기준으로 lambda를 적용하면 x는 컬럼내의 각각의 원소가 됨

In [16]:
# 4) StandardScaler()를 이용하여 스케일링하여라. 
scaler = StandardScaler()
scaler.fit(X_diabetes)
# ndarray로 나온다,
X_diabetes_scaled = scaler.transform(X_diabetes)

df_X_diabetes_scaled = pd.DataFrame(X_diabetes_scaled, columns = X_diabetes.columns)
df_X_diabetes_scaled

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
#                                                         random_state = 156, stratify=y)
# model_dt = DecisionTreeClassifier(random_state=11)

# 6) 오차행렬, 재현율, 정밀도, 정확도, F1 Score 등의 평가지표를 출력하여라 

# 7) 아래의 소스를 참조하여 그리드서치를 적용시켜 최고의 하이퍼파라미터 예측 모델을 생성하여라. 

# model_dt = DecisionTreeClassifier(random_state=11)

# parameters = {'max_depth':[2,3,5,10] }

# model_dt_grid = GridSearchCV(model_dt , param_grid=parameters , scoring='accuracy' , cv=5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.536251,0.865276,-0.021044,0.872057,-0.417768,0.167255,0.468492,1.425995
1,-1.140353,-1.205989,-0.516583,0.248678,-0.417768,-0.851535,-0.365061,-0.190672
2,1.206893,2.015979,-0.681762,-0.630654,-0.417768,-1.331821,0.604397,-0.105584
3,-1.140353,-1.074480,-0.516583,-0.374700,-0.265107,-0.633222,-0.920763,-1.041549
4,-0.186348,0.503626,-2.663916,0.872057,0.530423,1.549899,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.877535,-0.679954,0.309315,2.222711,0.659428,0.065376,-0.908682,2.532136
764,-0.805032,0.010468,-0.186224,0.040885,-0.417768,0.632988,-0.398282,-0.531023
765,0.200930,-0.022409,-0.021044,-0.374700,-0.071599,-0.909751,-0.685193,-0.275760
766,-1.140353,0.141977,-1.012121,-0.630654,-0.417768,-0.342140,-0.371101,1.170732
767,-1.140353,-0.942972,-0.186224,0.456471,-0.417768,-0.298477,-0.473785,-0.871374

In [17]:
# 5) 학습 데이타셋과 테스트 데이타셋으로 분리시키고 모델을 생성한 후 
#    머신러닝 예측 모델을 수립하고 학습하여라 
X_train, X_test, y_train, y_test = train_test_split(df_X_diabetes_scaled, Y_diabetes, test_size = 0.2, 
                                                    random_state = 156, stratify=Y_diabetes)

In [18]:
# KNN 기본값으로 수행 
model_kn = KNeighborsClassifier()
model_kn.fit(X_train, y_train)
accuracy_score(y_test, model_kn.predict(X_test))

0.7012987012987013

In [19]:
# 결정트리로 시작
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(random_state=11)
model_dt.fit(X_train, y_train)
accuracy = accuracy_score(y_test, model_dt.predict(X_test))
print(accuracy)

0.7402597402597403